name: Testing
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  test:
    name: Testing on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.12", "3.11", "3.10", 3.9, 3.8, pypy-3.9]
        os: ["ubuntu-22.04"]
        include:
          - os: "ubuntu-latest"
            python-version: 3.11
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-
      - name: pip version
        run: pip --version
      - name: Install dependencies
        run: python -m pip install tox
      - name: Run linting
        if: matrix.python-version == '3.9'
        run: tox -e lint
      # tests and coverage
      - name: Test
        run: tox -e test
      - name: Coverage
        run: coveralls --service=github
